services:
  cortei-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: cortei-server-dev
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_PATH=/app/data/appointments.db
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
      - MAX_DB_CONNECTIONS=10
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /app
          ignore:
            - tmp/
            - data/
            - vendor/
            - "*.db"
        - action: rebuild
          path: ./server/go.mod
        - action: rebuild
          path: ./server/go.sum
    volumes:
      - go-mod-cache:/go/pkg/mod
      - app_data_dev:/app/data
    networks:
      - cortei-network-dev
    stdin_open: true
    tty: true

volumes:
  go-mod-cache:
    driver: local
  app_data_dev:
    driver: local

networks:
  cortei-network-dev:
    driver: bridge
