root="."
tmp_dir="tmp"

[build]
cmd="sh -c 'mkdir -p ./tmp && if [ -d ./cmd/server ]; then go build -o ./tmp/main ./cmd/server; else go build -o ./tmp/main ./; fi'"
bin="tmp/main"
include_ext=["go","tpl","tmpl","html"]
exclude_dir=["tmp","vendor","data",".git"]

[log]
level="debug"
