// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Mutation struct {
}

type NewAppointmentInput struct {
	ClientName string `json:"clientName"`
	Date       string `json:"date"`
	Time       string `json:"time"`
}

type Query struct {
}
